# Exported from Render on 2025-10-14T04:17:10Z
version: "1"
services:
- type: web
  name: online-svm-system
  runtime: docker
  branch: production
  repo: https://github.com/LarTekmeng/svm-sys
  plan: free
  envVars:
  - key: NODE_ENV
    sync: false
  - fromGroup: svm-online-system
  region: singapore
  healthCheckPath: /health
  dockerContext: node_api
  dockerfilePath: node_api/Dockerfile
  autoDeployTrigger: commit
