services:
  - type: web
    name: online-svm-system
    env: docker
    plan: free
    branch: production           # must exist
    dockerfilePath: node_api/Dockerfile
    dockerContext: node_api
    autoDeploy: true
    healthCheckPath: /health     # you already have /health
    envVars:
      - key: NODE_ENV
        value: production
