services:
  - type: web
    name: online-svm-system
    runtime: docker
    plan: free
    branch: production
    dockerfilePath: node_api/Dockerfile
    dockerContext: node_api
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
