// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFiAK5L5xCM-Yqsaw6CYId8L6Hjbt2bMI',
    appId: '1:268501430444:web:34bb8516c6e279b3602f09',
    messagingSenderId: '268501430444',
    projectId: 'mobile-app-proj-bfbf2',
    authDomain: 'mobile-app-proj-bfbf2.firebaseapp.com',
    storageBucket: 'mobile-app-proj-bfbf2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2iG7SHQOgDhkSH1ze96mPQUbdsdr7E0k',
    appId: '1:268501430444:android:28fe3ddf85fc7b3e602f09',
    messagingSenderId: '268501430444',
    projectId: 'mobile-app-proj-bfbf2',
    storageBucket: 'mobile-app-proj-bfbf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlpL2kABR0i0R0Jqhb0FUrGOFddz0BmEk',
    appId: '1:268501430444:ios:c62faf300cb6b379602f09',
    messagingSenderId: '268501430444',
    projectId: 'mobile-app-proj-bfbf2',
    storageBucket: 'mobile-app-proj-bfbf2.firebasestorage.app',
    iosClientId: '268501430444-1v4p7qo3bfmvm2sgfit2khnk6vkhji4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineDocSavimex',
  );
}
